# Generated by Django 3.0.14 on 2023-04-28 16:32

import datetime
from django.db import migrations, models
import social_django.fields
import social_django.storage


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32)),
                ('next_step', models.PositiveSmallIntegerField(default=0)),
                ('backend', models.CharField(max_length=32)),
                ('data', social_django.fields.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 28, 22, 2, 39, 356756))),
            ],
            options={
                'db_table': 'social_auth_partial',
            },
            bases=(models.Model, social_django.storage.DjangoPartialMixin),
        ),
        migrations.AddField(
            model_name='code',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 28, 22, 2, 39, 356756)),
        ),
        migrations.AddField(
            model_name='usersocialauth',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 22, 2, 39, 356756)),
        ),
        migrations.AddField(
            model_name='usersocialauth',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersocialauth',
            name='pic',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usersocialauth',
            name='usercode',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='code',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='extra_data',
            field=social_django.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='uid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='utype',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterUniqueTogether(
            name='association',
            unique_together={('server_url', 'handle')},
        ),
    ]
